# Generated by Django 4.1.1 on 2022-10-03 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction",
            field=models.CharField(
                choices=[("in", "IN"), ("out", "OUT")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
