# Generated by Django 4.1.1 on 2022-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_transaction_transaction_alter_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="price_total",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
